import { ReactNode } from 'react'
import './globals.css'
import{ TodoList } from './components/Todolist'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  
}: {
  children: ReactNode
}) {
  return (
    <html className='bg-background1'>

  <body>
    <TodoList />
  </body>
    </html>
  
  )
}
